### ISSUE TITLE
CategoryMenu, TagMenu, AuthorMenu cannot be loaded

### ISSUE THREAD

**Issue by ngn1123** [django-blog-zinnia/cmsplugin-zinnia#43] opened 2015-01-23 16:19 UTC
I get the following errors:

Menu CategoryMenu cannot be loaded. Please, make sure all its urls exist and can be resolved
Menu TagMenu cannot be loaded. Please, make sure all its urls exist and can be resolved.
Menu AuthorMenu cannot be loaded. Please, make sure all its urls exist and can be resolved

I know that this issue was closed under issue #29 but I am getting the same issue now using the following versions: Django 1.7.3, Django CMS 3.0.9, Zinnia 0.15.1, and cmsplugin-zinnia 0.7. From my understanding of issue #29, the key to resolving this was using the latest version of zinnia, which we are right now.

Under installed apps, we have the following:
INSTALLED_APPS = (
    'djangocms_admin_style',
    'djangocms_text_ckeditor',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'django_comments',
    'mptt',
    'tagging',
    'zinnia',
    'cmsplugin_zinnia',
    'reversion',
    'rest_framework',
)

The weird thing about this issue is that it is inconsistent on each page load. Sometimes it pops up, and other times it doesn't, and this affects our deployment as we get an 502 Bad Gateway from nginx and in the uwsgi logs we were getting a: 
Django.db.utils.OperationalError: SSL error decryption failed or bad record mac

Any help would be much appreciated.

**Comment by abhishekreddy1206** [comment] 2015-01-23 16:29
Hi, I am also getting the same issue in production using the same latest versions of cms and zinnia

**Comment by Fantomas42** [comment] 2015-03-19 14:14
Hello,

I'm sorry but I have just done some tests with the recent versions of the CMS and the latest version of Zinnia and I cannot reproduce this error.

I have no idea from where this error is getting from...

I close the issue until more information.

Regards

**Closed by Fantomas42** 2015-03-19 14:14 UTC
